general:
  branches:
    only:
     - master

# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

#      Permission denied error, temporarily disabling cache
#      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "requirements.txt" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install -r requirements.txt
            mkdir artifacts
            cp sns_to_ses_mailer.py artifacts
            cp -r /usr/local/lib/python2.7/site-packages/jinja2 artifacts/
            cp -r /usr/local/lib/python2.7/site-packages/markupsafe artifacts/
            cd artifacts
            LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
            VERSION=$(echo $LATEST_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            VERSION_NUMBER=$(echo $VERSION | sed 's/^v\(.*\)$/\1/')
            zip -r aws-sns-to-ses-mailer-$VERSION_NUMBER.zip *

#      Permission denied error, temporarily disabling cache
#      - save_cache:
#          paths:
#            - /usr/local/lib/python2.7/site-packages/
#          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - store_artifacts:
          path: aws-sns-to-ses-mailer-0.0.1.zip
          destination: artifacts

      - persist_to_workspace:
          root: artifacts
          paths:
            - aws-sns-to-ses-mailer-0.0.1.zip
  publish-github-release:
      docker:
        - image: cibuilds/github:0.10
      steps:
        - attach_workspace:
            at: ./artifacts
        - run:
            name: "Publish Release on GitHub"
            command: |
              ls -la artifacts
              LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
              VERSION=$(echo $LATEST_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
              echo "ghr -t GITHUB_TOKEN -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/"
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
